import { getSiteId } from "./siteConfig";

export interface GuideRegion {
  name: string;
  theName: string;
  slug: string;
  mainCity: string;
  areas: string;
  locations: string[];
  /** Region-specific insights for guide content differentiation */
  insights?: {
    skipHire: string;
    vanHire: string;
    locksmith: string;
    removals: string;
    bouncy: string;
    limo: string;
    plant: string;
    pest: string;
    driving: string;
  };
}

const REGIONS: Record<string, GuideRegion> = {
  northeast: {
    name: "North East",
    theName: "the North East",
    slug: "north-east",
    mainCity: "Newcastle",
    areas: "Newcastle, Sunderland, Durham, Middlesbrough and Gateshead",
    locations: ["newcastle", "sunderland", "durham", "middlesbrough", "gateshead", "darlington"],
    insights: {
      skipHire: "North East councils including Newcastle City Council and Durham County Council have well-established online skip permit systems, typically processing applications within two to three working days. The region's network of household waste recycling centres at Byker, Campground and Alnwick provides free alternatives for items that cannot go in skips. Skip hire prices in the North East tend to be ten to fifteen percent below the national average.",
      vanHire: "The A1(M) corridor between Newcastle and Teesside drives strong demand for one-way van rentals, with many depots clustered around the Team Valley and Silverlink retail parks. Student moves between Durham, Newcastle and Northumbria universities create a pronounced September rental spike. The region's relatively compact geography means most local moves can be completed in a single day, keeping daily hire rates competitive.",
      locksmith: "Northumbria Police's secured-by-design recommendations are widely followed across Tyneside, and many locksmiths in the region hold SBD accreditation. Terraced housing stock in areas like Sunderland and South Shields often features older Yale-type locks that are straightforward to replace. Average emergency call-out times in urban Tyneside run around twenty to thirty minutes, though rural Northumberland can be over an hour.",
      removals: "The North East property market features some of the most affordable house prices in England, which drives high transaction volumes and steady demand for removal services. Popular moving corridors run between Tyneside and Teesside, with many families relocating from central Newcastle to County Durham commuter villages. Steep residential streets in areas like Gateshead and older Victorian terraces with no off-street parking can add complexity to moves.",
      bouncy: "The North East's large public parks like Jesmond Dene, Saltwell Park and Hardwick Park are popular venues for outdoor parties with bouncy castles from May through September. Coastal wind can be a factor for operators in areas like Whitley Bay and Tynemouth, requiring more robust anchoring. The region has a strong community fete culture, with village galas across County Durham generating consistent summer bookings.",
      limo: "Popular wedding venues including Linden Hall, Ellingham Hall and Wynyard Hall drive strong weekend demand for limousine and wedding car hire across the region. The Newcastle and Sunderland prom market peaks in late June and early July, with stretch limos and vintage cars both in high demand. Race days at Newcastle Racecourse and the Sunderland Airshow create additional seasonal booking clusters.",
      plant: "Major regeneration projects across Tyneside and Teesside, including ongoing development at the former Redcar steelworks site, sustain strong demand for excavators and heavy plant. The region's mix of clay and boulder clay subsoils means tracked excavators are preferred over wheeled machines for most groundwork. Smaller micro-diggers are increasingly popular for residential landscaping jobs in suburban areas of Darlington and Durham.",
      pest: "Rat populations along the Tyne and Wear river corridors are a persistent urban issue, with Newcastle and Gateshead councils reporting rising call-outs in recent years. Rural Northumberland properties face seasonal wasp nest problems from June through September, often in barns and outbuildings. Seagull nesting on rooftops in coastal towns like Whitby and Tynemouth has become a significant pest control niche.",
      driving: "North East test centres including Newcastle Gosforth, Sunderland and Durham have pass rates broadly in line with the national average at around forty-five to forty-eight percent. Learners face challenging conditions on the steep banks of the Tyne valley and multi-lane roundabouts on the A19 corridor. Heavy traffic around the Tyne Tunnel and Metro Centre provides useful real-world experience for new drivers preparing for their tests.",
    },
  },
  northwest: {
    name: "North West",
    theName: "the North West",
    slug: "north-west",
    mainCity: "Manchester",
    areas: "Manchester, Liverpool, Bolton, Preston and Warrington",
    locations: ["manchester", "liverpool", "bolton", "preston", "warrington", "stockport"],
    insights: {
      skipHire: "Greater Manchester's Clean Air Zone and Liverpool's evolving waste management policies mean skip operators must stay on top of changing permit and environmental requirements. The region has one of the highest construction waste recycling rates in England, with facilities at Pilsworth and Bredbury processing significant volumes. Skip prices in Manchester tend to be five to ten percent above the national average due to high demand from the region's booming housebuilding sector.",
      vanHire: "The M62 corridor connecting Manchester and Liverpool is one of the busiest freight routes in the UK, and van hire depots are heavily concentrated around Trafford Park, Haydock and Warrington. The region sees strong demand for larger panel vans during the January and summer sales periods, driven by the wholesale and retail sectors. Rental competition is fierce, with national chains and independent operators both well-represented across Greater Manchester.",
      locksmith: "Greater Manchester Police and Merseyside Police both maintain approved locksmith referral lists, and MLA-accredited locksmiths are strongly preferred in the region. Burglary hotspots in south Manchester and parts of Liverpool drive consistent demand for lock upgrades and security assessments. Urban response times across Manchester and Liverpool typically sit around fifteen to twenty-five minutes, benefiting from the region's dense motorway network.",
      removals: "The North West has one of the most active property markets outside London, with Manchester's rapid growth creating constant demand for both domestic and commercial removals. A major moving corridor runs between Liverpool and Manchester, with increasing numbers of families relocating to commuter towns like Warrington, Wigan and Chorley. Victorian terraced streets in Salford and Anfield present narrow access challenges, while high-rise apartments in Manchester city centre require lift booking and loading bay coordination.",
      bouncy: "The North West's extensive park infrastructure, including Heaton Park, Sefton Park and Williamson Park, provides excellent outdoor party venues throughout the summer months. The region's famously unpredictable weather means operators routinely offer indoor-compatible units and late cancellation policies. Lancashire's agricultural show circuit, including the Royal Lancashire Show, generates significant commercial bookings for inflatable entertainment.",
      limo: "Manchester's vibrant nightlife scene and Liverpool's hen and stag party market sustain year-round demand for limousine hire beyond the traditional wedding season. Iconic wedding venues like Peckforton Castle, Knowsley Hall and The Midland Hotel drive premium bookings. Chester Racecourse Ladies Day and the Grand National at Aintree create major seasonal spikes in luxury transport demand.",
      plant: "Manchester's skyline continues to transform with major residential and commercial developments, maintaining strong demand for tower cranes, excavators and concrete pumps. The region's peat-heavy ground conditions in parts of Lancashire and the Mersey basin often require specialist foundation equipment. A growing trend toward basement conversions in affluent areas like Alderley Edge and Hale has boosted demand for mini-excavators and muck-away services.",
      pest: "The Manchester Ship Canal and extensive Victorian sewer network contribute to persistent rat populations across Greater Manchester, with council pest control services under increasing pressure. Textile moths and carpet beetles are a notable problem in the region's older housing stock, particularly in areas with large numbers of pre-war properties. Rural Lancashire faces seasonal influxes of cluster flies and field mice as temperatures drop in autumn.",
      driving: "Manchester test centres including Cheetham Hill and Sale have historically lower pass rates than the national average, hovering around forty to forty-four percent due to complex urban road layouts. The region's extensive tram network requires learners to master shared road space with Metrolink vehicles, a challenge unique to Greater Manchester. Motorway driving on the M60 orbital and M62 provides essential experience, with many instructors incorporating slip-road joining as a core lesson element.",
    },
  },
  scotland: {
    name: "Scotland",
    theName: "Scotland",
    slug: "scotland",
    mainCity: "Glasgow",
    areas: "Glasgow, Edinburgh, Aberdeen, Dundee and Inverness",
    locations: ["glasgow", "edinburgh", "aberdeen", "dundee", "inverness", "stirling"],
    insights: {
      skipHire: "Scottish councils operate under different waste regulations to England, with the Scottish Environment Protection Agency (SEPA) overseeing skip operator licensing and waste carrier permits. Edinburgh's World Heritage Site status means skip placement in the Old Town and New Town requires special heritage consent on top of standard road occupation permits. Scotland's landfill tax is set independently from England and has historically been slightly higher, which pushes skip operators toward recycling and keeps prices marginally above English averages.",
      vanHire: "The M8 between Glasgow and Edinburgh is Scotland's busiest route and many van hire depots cluster around Glasgow's Hillington industrial estate and Edinburgh's Newbridge area. Long-distance rentals for Highland and island moves are common, with many operators offering one-way drop-offs at Inverness and Aberdeen at a premium. Winter conditions on routes like the A9 mean four-wheel-drive vans and vehicles with winter tyres are in demand from November to March.",
      locksmith: "Police Scotland maintains a single national framework for security advice, and locksmiths with SBD or MLA accreditation are recommended across the country. Tenement flats in Glasgow and Edinburgh frequently have communal entry systems and mortice locks that require specialist knowledge. Emergency response times vary dramatically, with central Glasgow averaging under twenty minutes but rural Highland call-outs sometimes exceeding two hours.",
      removals: "Scotland's property market operates under a different legal system with home reports and a sealed-bid process, which can lead to faster completion timelines and shorter notice periods for removal bookings. The Glasgow-to-Edinburgh corridor is the busiest moving route, though a growing trend sees families relocating from the Central Belt to towns like Perth, Stirling and Dunfermline. Multi-storey tenement flats without lifts in Glasgow's West End and Edinburgh's Marchmont present significant stair-carry challenges for removal crews.",
      bouncy: "Scotland's outdoor party season is shorter than England's, typically running from late May to early September, which compresses demand into a busy peak period. Castle grounds and estate venues like Glamis Castle and Blair Drummond Safari Park are popular settings for events with inflatable entertainment. Scottish weather requires operators to be especially vigilant about wind conditions, and many carry anemometers as standard equipment.",
      limo: "Edinburgh's festival season in August generates exceptional demand for luxury transport, with Fringe performers and festival-goers booking everything from classic cars to stretch limousines. Iconic Scottish wedding venues including Gleneagles, Loch Lomond and Eilean Donan Castle sustain a premium wedding car market. The Ayrshire coast and St Andrews are popular destinations for golf-related luxury transport packages.",
      plant: "Scotland's ambitious housebuilding targets and major infrastructure projects, including ongoing improvements to the A9 dualling programme, drive sustained plant hire demand. Soft, waterlogged ground conditions across much of the Highlands and Western Scotland mean low-ground-pressure tracked machines are essential for many projects. Aberdeen's oil and gas decommissioning sector creates a specialist market for heavy lifting equipment and crane hire.",
      pest: "Scotland's midges are infamous in the Highlands from June to August, and while not a traditional pest control issue, many Scottish operators offer midge barrier treatments for outdoor events and hospitality venues. Urban rat populations in Glasgow and Edinburgh are a persistent problem, with Glasgow City Council running dedicated rodent control programmes. Red squirrel conservation programmes mean grey squirrel management is a notable pest control niche in parts of the Borders and Perthshire.",
      driving: "Scottish driving test centres operate under the same DVSA framework as England, but centres like Glasgow Anniesland and Edinburgh Currie have pass rates around forty-two to forty-five percent, slightly below the UK average. Learners in Scotland face unique challenges including single-track roads with passing places in rural areas and steep hill starts in cities like Edinburgh and Stirling. Winter driving conditions with ice and snow are more prevalent and prolonged than in most English regions, making winter lessons a valuable part of instructor programmes.",
    },
  },
  midlands: {
    name: "Midlands",
    theName: "the Midlands",
    slug: "midlands",
    mainCity: "Birmingham",
    areas: "Birmingham, Nottingham, Leicester, Coventry and Derby",
    locations: ["birmingham", "nottingham", "leicester", "coventry", "derby", "wolverhampton"],
    insights: {
      skipHire: "Birmingham City Council processes skip permits online with a typical turnaround of three to five working days, though permits on A-roads and city centre locations can take longer due to traffic management requirements. The Midlands has a dense network of waste transfer stations, with major facilities at Tyseley, Aldridge and Castle Donington offering competitive tipping rates. The concentration of construction activity around Birmingham and the HS2 route has pushed skip hire prices up in the West Midlands compared to surrounding areas.",
      vanHire: "The Midlands sits at the heart of the UK motorway network where the M1, M6, M42 and M5 converge, making it a natural hub for van hire with excellent connectivity in every direction. Major distribution centres around East Midlands Airport, Corby and Rugby mean there is a large fleet of commercial vehicles available in the region. The region's strong manufacturing and logistics sector generates consistent weekday demand for transit-sized vans, keeping utilisation rates and prices relatively high.",
      locksmith: "West Midlands Police and Nottinghamshire Police both recommend using locksmiths registered with the MLA, and the region has a well-developed network of accredited emergency operators. The Midlands' diverse housing stock, from canal-side conversions in Birmingham to older terraces in the Potteries, means locksmiths need expertise across a wide range of lock types. Response times in the Birmingham and Nottingham conurbations are typically under twenty minutes, with rural Shropshire and Herefordshire adding significantly to call-out distances.",
      removals: "The Midlands property market benefits from relatively affordable prices compared to the South East, driving high transaction volumes particularly among first-time buyers in cities like Nottingham, Leicester and Coventry. A major moving corridor runs along the M1 between Nottingham, Leicester and London, with many families relocating north for better value. Birmingham's growing population of high-rise city centre apartments presents logistical challenges with loading bays, service lifts and parking restrictions.",
      bouncy: "The Midlands' large suburban population with spacious gardens makes it one of the strongest regions in England for residential bouncy castle hire. Showgrounds at the NEC, Donington Park and the Three Counties Showground host regular large-scale family events with inflatable zones. The region enjoys a relatively sheltered inland climate, though summer thunderstorms can cause last-minute cancellations between June and August.",
      limo: "The Midlands is home to some of England's most popular wedding venues, including Warwick Castle, Stapleford Park and Weston Park, which drive strong demand for wedding cars and vintage vehicle hire. Birmingham's vibrant nightlife in the Broad Street area generates consistent Friday and Saturday evening bookings for party limousines. The NEC exhibition centre and Resorts World create year-round demand for corporate and VIP transport services.",
      plant: "HS2 construction through the West Midlands has been a major driver of plant hire demand, with large excavators, piling rigs and earthmoving equipment in sustained demand across the route. The East Midlands' quarrying industry around Leicestershire and Derbyshire means crushing and screening equipment is readily available for hire. Mixed ground conditions, from sandstone in Nottingham to heavy Warwickshire clay, require operators to match equipment carefully to local geology.",
      pest: "The Midlands' canal network, including the Birmingham Canal Navigations with over a hundred miles of urban waterway, creates persistent rat harbourage and activity corridors through residential areas. Asian hornets have been identified in parts of the West Midlands, putting pest controllers on alert for this invasive species. The region's mix of industrial heritage sites and Victorian housing stock provides ideal conditions for pigeon and feral bird infestations in city centres.",
      driving: "Birmingham test centres including Kingstanding, Shirley and Sutton Coldfield have pass rates varying from thirty-eight to forty-eight percent, reflecting the diversity of road conditions across the city. The Midlands' complex junction layouts, including Spaghetti Junction and the A38 Aston Expressway, provide challenging but valuable learning environments. Learners in the East Midlands benefit from a good mix of urban, rural and dual carriageway roads within short distances of most test centres.",
    },
  },
  yorkshire: {
    name: "Yorkshire",
    theName: "Yorkshire",
    slug: "yorkshire",
    mainCity: "Leeds",
    areas: "Leeds, Sheffield, Bradford, York and Hull",
    locations: ["leeds", "sheffield", "bradford", "york", "hull", "wakefield"],
    insights: {
      skipHire: "Yorkshire councils have varying skip permit systems, with Leeds City Council offering same-day online applications while Sheffield typically requires two to three working days for processing. The region's strong demolition and reclamation industry, particularly around Rotherham and Doncaster, means waste transfer station competition keeps tipping fees competitive. Flooding risk along the Aire and Ouse valleys means some operators are cautious about placing skips in low-lying areas during winter months.",
      vanHire: "The M62 trans-Pennine route and the M1 north-south corridor make Yorkshire a natural crossroads for van hire, with major depots around Leeds Bradford, Sheffield and Hull docks. Student populations in Leeds, Sheffield and York create intense September demand, with many rental fleets fully booked weeks in advance for the university move-in period. Hull's position as a major port generates demand for transit vans among import and export businesses moving goods to and from the ferry terminals.",
      locksmith: "West Yorkshire Police and South Yorkshire Police both emphasise the importance of using MLA-registered locksmiths, particularly following spates of lock-snapping burglaries targeting euro-cylinder locks across the region. Stone-built properties in the Yorkshire Dales and North York Moors often have older, non-standard door furniture requiring specialist knowledge. Urban response times in Leeds and Sheffield are consistently under twenty minutes, though the Dales and Moors can mean forty-five-minute-plus waits.",
      removals: "Yorkshire's property market offers significantly better value than the South East, attracting relocating families from London and the Home Counties along a well-established M1 moving corridor. Sheffield's famous hills, particularly in areas like Crookes, Walkley and Stannington, present genuine physical challenges for removal crews and require experienced drivers for large vehicles. York's medieval street layout with narrow lanes and limited parking means removals in the city centre often need early-morning or evening time slots with temporary parking suspensions.",
      bouncy: "Yorkshire's large green spaces, including Roundhay Park, the Sheffield Botanical Gardens and the Stray in Harrogate, are popular venues for outdoor events with inflatable entertainment. The Pennine weather brings higher rainfall and stronger winds to western Yorkshire, leading many operators to favour indoor soft play hire alongside outdoor inflatables. Yorkshire's agricultural show calendar, including the Great Yorkshire Show at Harrogate, provides a significant commercial booking pipeline for inflatable operators.",
      limo: "Stately home wedding venues including Allerton Castle, Rudding Park and Wentworth Woodhouse sustain a premium wedding car market across Yorkshire. York's compact medieval centre makes vintage wedding cars particularly photogenic, and operators report strong demand for classic vehicles over modern limousines. Sheffield and Leeds prom season runs from late June into July, with school leavers increasingly opting for novelty vehicles alongside traditional stretch limousines.",
      plant: "South Yorkshire's ongoing transformation from its industrial heritage has produced major brownfield regeneration sites requiring specialist demolition and remediation plant. The region's geology varies dramatically from soft coal measures in South Yorkshire to hard millstone grit in the Pennines, requiring different drilling and excavation approaches. Flood alleviation schemes along the Don, Aire and Calder valleys have created a steady pipeline of civil engineering plant hire demand.",
      pest: "Yorkshire's extensive farming landscape means rural properties face seasonal invasions of rats and mice, particularly after harvest when rodents move indoors seeking food and shelter. Coastal areas around Scarborough and Bridlington experience significant seagull nesting problems, with the protected status of herring gulls requiring licensed pest controllers for nest management. Sheffield's woodland setting brings foxes and grey squirrels into suburban gardens more frequently than in many other English cities.",
      driving: "Yorkshire test centres show significant variation in pass rates, with York averaging around fifty percent while Bradford sits closer to thirty-eight percent, reflecting very different road environments. Learners in the region must contend with steep Pennine roads, exposed moorland crossings and complex urban one-way systems in Leeds and Sheffield. The prevalence of rural B-roads with blind bends and livestock hazards makes Yorkshire driving lessons particularly thorough preparation for real-world conditions.",
    },
  },
  east: {
    name: "East of England",
    theName: "the East of England",
    slug: "east-of-england",
    mainCity: "Norwich",
    areas: "Norwich, Cambridge, Ipswich, Colchester and Chelmsford",
    locations: ["norwich", "cambridge", "ipswich", "colchester", "chelmsford", "peterborough"],
    insights: {
      skipHire: "East of England councils generally process skip permits within three working days, though Cambridge City Council's conservation areas and narrow medieval streets often require additional traffic management assessments. The region's flat agricultural landscape means many rural properties have ample space for skip placement without needing road permits. Landfill capacity across Norfolk and Suffolk remains relatively good compared to southern England, helping to keep tipping fees and skip hire prices moderate.",
      vanHire: "The A14 corridor between the Midlands and Felixstowe port drives significant commercial van hire demand, with logistics businesses moving goods between the UK's busiest container port and inland distribution centres. Cambridge's booming tech sector generates steady weekday demand for medium-sized vans used in office relocations and equipment transport. The region's predominantly rural character means mileage-inclusive rental packages are particularly popular, as journeys between towns tend to be longer than in more urban regions.",
      locksmith: "Norfolk and Suffolk Constabularies recommend MLA-accredited locksmiths, and the region's dispersed rural population means response times outside major towns can stretch to an hour or more. Period properties in market towns like Bury St Edmunds, Saffron Walden and Woodbridge frequently have non-standard locks and heritage door furniture that require specialist skills. The Cambridge college accommodation market generates consistent term-time demand for lock changes and access control work.",
      removals: "The East of England has seen significant population growth driven by London overspill, with families relocating from the capital to towns like Chelmsford, Colchester and Peterborough along well-established commuter corridors. Rural Norfolk and Suffolk properties often have long, unpaved driveways and remote locations that can add time and complexity to moves. The region's flat terrain and generally wide roads make it physically easier for large removal vehicles compared to hillier parts of the country.",
      bouncy: "The East of England's relatively dry, sunny climate, particularly along the Suffolk and Norfolk coast, makes it one of the better regions for outdoor inflatable hire from April through October. Village fetes and church fundraisers are a significant part of the rural social calendar, generating steady bookings for bouncy castle operators across the region. Large private gardens in affluent areas like the Cambridge suburbs and north Essex provide ideal settings for residential party hire.",
      limo: "Country house wedding venues including Hengrave Hall, Hedingham Castle and Chippenham Park House drive strong demand for vintage and classic wedding car hire across the region. Cambridge May Balls and college events create a unique seasonal niche for luxury transport in late June that is unlike any other region. The Newmarket racing calendar, including prestigious race days at the July Course, generates demand for premium chauffeur and limousine services.",
      plant: "Cambridge's rapid expansion with major developments at Eddington, Marleigh and the Biomedical Campus has created sustained demand for construction plant across the region. The region's heavy clay and chalky boulder clay soils in parts of Essex and Suffolk mean foundation work often requires powerful tracked excavators. The Fens present unique ground conditions with soft peat soils, where specialist low-ground-pressure machinery is essential to avoid costly ground damage.",
      pest: "The East of England's extensive agricultural landscape makes it a particular hotspot for rat and mouse infestations in rural properties, barns and grain stores, especially after harvest season. Coastal areas from Essex through Suffolk to Norfolk experience persistent seagull problems, and the region's numerous waterways attract mink, which threaten native wildlife and require professional trapping. The warmer, drier climate of East Anglia compared to western England supports larger wasp populations, with nest removals peaking between July and September.",
      driving: "East of England test centres including Norwich, Ipswich and Bury St Edmunds tend to have above-average pass rates, often exceeding fifty percent, partly due to less congested road conditions. The region's extensive network of rural A-roads and single carriageways provides learners with experience of overtaking, tractors and country road hazards that urban-only learners miss. Cambridge presents a unique learning environment with heavy bicycle traffic, bus lanes and a complex one-way system that requires excellent observation and anticipation skills.",
    },
  },
  london: {
    name: "London",
    theName: "London",
    slug: "london",
    mainCity: "London",
    areas: "Central London, North London, South London, East London and West London",
    locations: ["london", "croydon", "bromley", "enfield", "barnet", "ealing"],
    insights: {
      skipHire: "London borough skip permit costs are the highest in the country, with some boroughs charging over sixty pounds per permit, and application processing can take up to five working days in busy periods. The congestion charge and ULEZ mean skip lorry operators face additional daily costs when working in central and inner London, which is reflected in higher prices. Space constraints on London's narrow residential streets often mean mini skips and midi skips are far more popular than the larger sizes common elsewhere in the UK.",
      vanHire: "London's ULEZ requirements mean all hire vans must meet Euro 6 diesel or Euro 4 petrol standards, and most major operators have fully updated their London fleets accordingly. Weekend demand for self-drive vans peaks dramatically as London renters move frequently between short-term lets, creating near-total fleet sellouts on Saturdays. Parking and loading restrictions across London boroughs mean hirers often need to factor in permit costs and time-limited loading bays when planning their jobs.",
      locksmith: "The Metropolitan Police Service recommends MLA-accredited locksmiths and the sheer density of London's locksmith market means response times in central London can be as fast as ten to fifteen minutes. London's mix of Victorian conversions, purpose-built flats and modern apartment blocks means locksmiths encounter the widest variety of lock types and access control systems in the country. The high proportion of rented accommodation drives consistent demand for lock changes between tenancies, making it the largest single market segment for London locksmiths.",
      removals: "London's property market is the most expensive in the UK, and the high cost of living drives a significant outward migration pattern with families relocating to the Home Counties, the South East and beyond. Moving within London presents unique challenges including parking suspension permits that must be arranged with individual boroughs, narrow stairwells in Victorian conversions and low-clearance railway bridges. Many London removal companies specialise in apartment moves with portering services, offering man-and-van packages tailored to the capital's compact living spaces.",
      bouncy: "London's parks require specific event permits for bouncy castle use, with councils like Lambeth, Wandsworth and Richmond each having different application processes and fee structures. The capital's vast indoor venue market means London bouncy castle operators often do a higher proportion of indoor bookings year-round compared to other regions. Community events in London's diverse neighbourhoods generate consistent demand for inflatables at cultural festivals, school fairs and estate fun days throughout the summer.",
      limo: "London's world-renowned luxury hotel circuit, including The Ritz, Claridge's and The Savoy, sustains a premium chauffeur and limousine market that operates year-round rather than seasonally. Prom bookings from the capital's large secondary school population make June and July the busiest months for stretch limousine operators. Theatre district drop-offs, corporate hospitality at venues like The O2 and Wembley, and airport transfers to Heathrow and City Airport provide steady midweek business that other regions lack.",
      plant: "London's construction boom, from Battersea Power Station to the ongoing Old Oak Common development, means plant hire demand in the capital consistently outstrips supply for larger equipment. Strict noise and emissions regulations in many London boroughs require electric or hybrid plant for inner-city projects, and operators offering low-emission equipment command premium rates. Space-constrained London building sites rely heavily on compact plant including micro-excavators, tracked dumpers and spider cranes that can navigate tight access routes.",
      pest: "London's ageing Victorian sewer system and dense built environment create ideal conditions for one of the largest urban rat populations in Europe, with boroughs like Westminster, Camden and Southwark reporting the highest call-out rates. Bed bug infestations have risen significantly across London's hotel and rental property sectors, creating a specialist treatment market that barely exists in most other UK regions. Urban foxes are present across almost every London borough, and while not a traditional pest, damage to gardens and disturbance to residents generates growing demand for humane deterrent services.",
      driving: "London driving test centres have some of the lowest pass rates in the country, with centres like Belvedere, Erith and Wood Green averaging around thirty-five to forty percent. The capital's complex road environment, including bus lanes, cycle superhighways, congestion charge boundaries and aggressive traffic, makes London one of the most challenging places in the UK to learn to drive. Many London learners require significantly more lessons than the national average, and instructors must teach pupils to handle situations rarely encountered elsewhere, such as box junctions, red routes and advanced stop lines for cyclists.",
    },
  },
  southeast: {
    name: "South East",
    theName: "the South East",
    slug: "south-east",
    mainCity: "Brighton",
    areas: "Brighton, Southampton, Reading, Oxford and Guildford",
    locations: ["brighton", "southampton", "reading", "oxford", "guildford", "maidstone"],
    insights: {
      skipHire: "South East councils tend to have stricter enforcement of skip permit conditions than other regions, with councils like Brighton and Hove requiring reflective markings and lighting on all road-placed skips from dusk. The region's high property density and limited road space, particularly in historic towns like Canterbury, Winchester and Chichester, make careful skip placement essential. Higher land values and disposal costs in the South East push skip hire prices ten to twenty percent above the national average.",
      vanHire: "The M25 orbital and M3/M23 corridors make the South East one of the busiest regions for van hire, with major depot clusters around Gatwick, Southampton docks and the Reading/Basingstoke corridor. The region's proximity to cross-Channel ports at Dover and Folkestone generates strong demand for vans equipped for European travel, with many operators offering channel crossing packages. High property costs drive frequent house moves and a large self-storage market, both of which sustain consistent van rental demand throughout the year.",
      locksmith: "Surrey Police, Hampshire Constabulary and Kent Police all recommend using locksmiths from recognised trade bodies, and the South East has one of the highest concentrations of MLA members in the country. The region's affluent commuter belt areas around Guildford, Sevenoaks and St Albans drive strong demand for high-security lock installations and smart lock upgrades. Coastal towns including Brighton, Portsmouth and Margate see seasonal spikes in lock-out calls during the holiday rental season.",
      removals: "The South East is the second most expensive property market in England after London, and the outward migration of London families into Kent, Surrey and Hampshire creates a constant flow of removal business along commuter corridors. Properties in the region range from compact seaside flats in Brighton to large rural farmhouses in the Surrey Hills, requiring removal companies to maintain versatile fleet sizes. Narrow lanes in the Kent Weald and Sussex Downs, combined with listed building access constraints, frequently require smaller shuttle vehicles to complete moves.",
      bouncy: "The South East's generally warmer and drier climate compared to northern regions extends the outdoor bouncy castle season, with operators often busy from Easter through to half-term in October. The region's large number of country house gardens, village greens and National Trust properties provide premium outdoor event settings. Brighton Pride, numerous regatta events along the south coast and the Surrey Hills show circuit create significant commercial booking opportunities for inflatable operators.",
      limo: "The South East hosts some of England's most prestigious wedding venues, including Leeds Castle, Goodwood House and Farnham Castle, sustaining year-round demand for luxury wedding transport. Epsom Derby, Royal Ascot and Glorious Goodwood race meetings create concentrated bursts of demand for chauffeur-driven luxury vehicles. The proximity to Gatwick and Heathrow airports makes airport limousine transfers a significant revenue stream for South East operators, unlike in more distant regions.",
      plant: "Major infrastructure projects including Lower Thames Crossing works and continued development along the M3 and M23 corridors maintain strong demand for heavy civil engineering plant across the region. The South East's chalk and clay subsoils can be challenging, with clay heave risk in parts of Surrey and Kent requiring careful foundation equipment selection. The region's strict planning controls in Areas of Outstanding Natural Beauty, including the North and South Downs, often mandate smaller, lower-impact equipment for approved projects.",
      pest: "The South East's warmer climate makes it the first region in the UK to experience seasonal pest activity each spring, with wasp nests and ant infestations appearing weeks earlier than in northern regions. Coastal areas face significant seagull problems during breeding season, with Brighton and Hastings councils receiving hundreds of complaints annually. The region is on the frontline for invasive species including Asian hornets, with confirmed sightings in Kent requiring rapid response from specially trained pest controllers.",
      driving: "South East test centres show wide variation in pass rates, with rural centres like Burgess Hill and Ashford often exceeding fifty percent while urban centres in Reading and Southampton sit closer to forty-three percent. The region offers learners an excellent mix of road types within short distances, from country lanes in the Weald to dual carriageways on the A3 and complex roundabouts on the M25 junction approaches. High traffic density, particularly during commuter hours on routes into London, gives South East learners practical experience of congested driving conditions that serves them well after passing.",
    },
  },
  southwest: {
    name: "South West",
    theName: "the South West",
    slug: "south-west",
    mainCity: "Bristol",
    areas: "Bristol, Bath, Exeter, Plymouth and Swindon",
    locations: ["bristol", "bath", "exeter", "plymouth", "swindon", "gloucester"],
    insights: {
      skipHire: "Bath and North East Somerset Council applies particularly strict skip permit conditions within the UNESCO World Heritage Site, requiring heritage-sensitive placement and sometimes refusing permits on Georgian streets entirely. The South West's lower population density and longer travel distances between waste facilities mean skip operators often factor in higher transport costs, though these are offset by lower land and tipping fees than in the South East. Cornwall and Devon councils have invested heavily in recycling infrastructure, with the region achieving some of the highest household recycling rates in England.",
      vanHire: "The M5 motorway is the primary arterial route for the South West, and van hire depots are concentrated around Bristol, Exeter and the Bridgwater gateway to Somerset and Devon. Seasonal tourism drives dramatic summer demand spikes, with holiday cottage changeover days, festival logistics and surfing equipment transport creating a rental pattern unlike any other English region. The region's narrow Devon and Cornwall lanes mean many hirers specifically request compact vans rather than the larger panel vans popular in urban areas.",
      locksmith: "Devon and Cornwall Police and Avon and Somerset Police both recommend using MLA or NCFE-accredited locksmiths, though the region's rural geography means emergency response times outside Bristol and Exeter can exceed an hour. Coastal properties face accelerated lock corrosion from salt air, and locksmiths in seaside towns like St Ives, Padstow and Lyme Regis regularly replace weather-damaged hardware. The large holiday let market across Devon and Cornwall generates consistent demand for key safe installations and access management systems.",
      removals: "The South West attracts significant numbers of retirees and remote workers relocating from London and the South East, creating a strong one-directional moving pattern into the region along the M4 and M5 corridors. Devon and Cornwall's narrow lanes, steep hills and remote rural properties present genuine logistical challenges, with many removal firms operating smaller shuttle vehicles to access properties where full-size lorries cannot reach. Bristol's rapidly growing city centre, with its Victorian terraces and modern waterfront apartments, presents classic urban moving challenges including permit parking and narrow stairwell access.",
      bouncy: "The South West's outdoor events season benefits from the region's mild maritime climate, though Atlantic weather systems can bring sudden rain and strong coastal winds that require robust anchoring. Festival culture is deeply embedded in the South West, with events from Glastonbury to local village fairs creating a thriving market for inflatable entertainment hire. Cornwall and Devon's tourism economy means bouncy castle operators often serve holiday parks, caravan sites and resort complexes alongside the traditional residential party market.",
      limo: "The South West offers some of England's most picturesque wedding venue settings, including Bovey Castle, The Lost Gardens of Heligan and Thornbury Castle, where vintage and classic wedding cars are strongly favoured. Bath's Georgian architecture provides a stunning backdrop for wedding transport photography, making it one of the most sought-after pickup locations in the region. The Cheltenham Gold Cup, Bath Races and Royal Bath and West Show generate concentrated seasonal demand for luxury transport services.",
      plant: "Bristol's ongoing urban expansion and regeneration around Temple Quarter and the Western Harbour has maintained strong plant hire demand in the city, while major road improvements on the A303 and North Devon Link Road create civil engineering opportunities. The South West's varied geology, from soft Somerset clay to hard Dartmoor granite, means plant operators must match equipment to dramatically different ground conditions within relatively short distances. Devon and Cornwall's isolated rural building sites often require self-loading equipment that can be transported on narrow single-track roads without escort vehicles.",
      pest: "The South West's mild, damp climate creates ideal conditions for fleas, which thrive in the region's many properties with pet-owning residents and are one of the most common domestic pest call-outs. Coastal towns across Devon, Cornwall and Dorset face significant seagull problems, with Exeter, Plymouth and Falmouth all running council-backed deterrent programmes. The region's extensive rural landscape means badger sett management and mole control are more common pest control services here than in most other English regions.",
      driving: "South West test centres are spread across large distances, with many learners in rural Devon and Cornwall needing to travel over thirty miles to reach their nearest centre. Pass rates at rural centres like Taunton and Truro tend to be above the national average at around fifty percent, while Bristol's urban centres sit closer to forty-three percent. The region's winding A-roads, steep Devon hills and single-track lanes with passing places give learners practical experience of road conditions that are among the most varied and demanding in England.",
    },
  },
  wales: {
    name: "Wales",
    theName: "Wales",
    slug: "wales",
    mainCity: "Cardiff",
    areas: "Cardiff, Swansea, Newport, Wrexham and Bangor",
    locations: ["cardiff", "swansea", "newport", "wrexham", "bangor", "aberystwyth"],
    insights: {
      skipHire: "Welsh councils operate under Natural Resources Wales rather than the English Environment Agency, and skip operators must hold separate Welsh waste carrier registrations. Bilingual signage requirements apply to skip permits in many Welsh local authorities, and Cardiff Council's online permit system is one of the more streamlined in the country with two-day turnaround. Landfill disposal rates in Wales have fallen dramatically due to the Welsh Government's aggressive recycling targets, which has pushed skip operators toward segregated waste services and higher recycling rates than most English regions.",
      vanHire: "The M4 corridor from Newport through Cardiff to Swansea is the main artery for van hire in South Wales, with most depots clustered around Cardiff and Newport's industrial estates. North Wales van hire is closely linked to the Merseyside and Cheshire markets, with many hirers crossing the border for competitive rates at depots in Chester and Wrexham. The Welsh tourism season creates strong summer demand for larger vans to transport equipment for outdoor activities, camping holidays and festival setups.",
      locksmith: "The four Welsh police forces recommend using locksmiths registered with the MLA, and the dispersed rural population across mid-Wales means emergency response times outside Cardiff and Swansea can exceed ninety minutes. Many older Welsh properties, particularly stone farmhouses and terraced miners' cottages in the Valleys, have non-standard door sizes and lock fittings that require adaptable skills. The growing student population in Cardiff, Swansea and Aberystwyth generates consistent demand for lock changes and HMO compliance work.",
      removals: "Wales has seen a significant influx of relocating families and remote workers from English cities since the pandemic, with the M4 corridor towns of Newport, Cardiff and Bridgend particularly popular. Removals in the Valleys face steep, narrow terraced streets with limited turning and parking, and many operators use smaller vehicles to shuttle loads to larger lorries parked on main roads. North Wales removals often involve long drives to and from English cities via the A55, and cross-border moves between North Wales and the North West of England are among the most common routes.",
      bouncy: "Wales's outdoor party season is weather-dependent, with the south coast around Gower and Pembrokeshire enjoying milder conditions than the more exposed north and mid-Wales areas. The Welsh tradition of community eisteddfodau, agricultural shows and chapel fundraisers provides a reliable stream of bookings for inflatable entertainment operators. Indoor leisure centres and community halls are more commonly used for bouncy castle parties in Wales than in southern England, reflecting the region's wetter climate.",
      limo: "Welsh wedding venues including St Donat's Castle, Fairy Hill on Gower and Portmeirion in Gwynedd attract couples from across the UK and drive demand for premium wedding transport. Cardiff's nightlife in the city centre, particularly around St Mary Street and the Bay, sustains Friday and Saturday evening limousine bookings. International rugby match days at the Principality Stadium create intense short-term demand for luxury group transport, with operators fully booked months in advance for Six Nations weekends.",
      plant: "The South Wales Valleys regeneration programme and ongoing development around Cardiff Bay and the city centre maintain steady plant hire demand, while the A465 Heads of the Valleys dualling project has been a major long-term customer. Wales's challenging terrain, from steep Valley slopes to waterlogged upland peat, requires careful equipment matching and experienced operators. The growing Welsh renewable energy sector, including onshore wind farm construction and maintenance in mid-Wales and Powys, has created a specialist market for tracked plant and all-terrain access equipment.",
      pest: "Wales's wet climate and extensive rural landscape create ideal conditions for rat populations, with farmyard infestations particularly common in the Valleys and across mid-Wales agricultural areas. The prevalence of old stone-built properties with lime mortar and cavity walls provides excellent harbourage for rodents, cluster flies and wasp nests. Coastal towns like Tenby, Aberystwyth and Llandudno face seasonal seagull problems during nesting season, and Welsh Government regulations on bird control can differ from English guidance.",
      driving: "Welsh driving test centres are widely spread, with learners in rural mid-Wales sometimes travelling over forty miles to Aberystwyth or Newtown for their tests. Pass rates vary significantly, with rural centres like Bangor and Haverfordwest achieving around fifty to fifty-five percent while Cardiff and Swansea urban centres sit closer to forty-five percent. Learners in Wales face unique road conditions including steep mountain passes, livestock on unfenced roads and bilingual road signage that requires additional observation skills.",
    },
  },
};

export function getGuideRegion(): GuideRegion | null {
  return REGIONS[getSiteId()] || null;
}
